name: ${CONTAINER_NAME}

services:
    portainer-ce:
        #ports:
        #    - '9000:9000'
        #    - '9443:9443'
        network_mode: frontend
        container_name: ${CONTAINER_NAME}
        restart: unless-stopped
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - './data:/data'
        image: 'portainer/portainer-ce:latest'
        env_file:
        - .env
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${CONTAINER_NAME}.entrypoints=http"
        - "traefik.http.routers.${CONTAINER_NAME}.rule=Host(`${CONTAINER_NAME}.${DOMAIN}`)"
        - "traefik.http.middlewares.${CONTAINER_NAME}-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.${CONTAINER_NAME}.middlewares=${CONTAINER_NAME}-https-redirect"
        - "traefik.http.routers.${CONTAINER_NAME}-secure.entrypoints=https"
        - "traefik.http.routers.${CONTAINER_NAME}-secure.rule=Host(`${CONTAINER_NAME}.${DOMAIN}`)"
        - "traefik.http.routers.${CONTAINER_NAME}-secure.tls=true"
        - "traefik.http.routers.${CONTAINER_NAME}-secure.service=${CONTAINER_NAME}"
        - "traefik.http.services.${CONTAINER_NAME}.loadbalancer.server.port=9000"
        - "traefik.docker.network=frontend"
networks:
  frontend:
    external: true
