#version: '3.3'
name: portainer

services:
    portainer-ce:
        ports:
            - '9000:9000'
            - '9443:9443'
        network_mode: frontend
        container_name: portainer
        restart: unless-stopped
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '.:/data'
        image: 'portainer/portainer-ce:latest'
