version: '3.5'
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=996
      - JELLYFIN_PublishedServerUrl=https://jellyfin.sample.org #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
    networks:
      - frontend

networks:
  frontend: 
    external: true # add this if the network is already existing!