version: "3"
services:
  samba:
    build: ./build
    image: kimostberg/samba
    restart: unless-stopped
    container_name: samba
    volumes:
      - ./public:/public
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    command: '-s "public;/public;yes;no;yes" -u "user;password" -p'
    networks:
      - frontend

networks:
  frontend: 
    external: true # add this if the network is already existing!