name: nebula-sync

services:
  nebula-sync:
    networks:
      - frontend
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    restart: unless-stopped    
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro

networks:
  frontend:
    external: true