services:
  client:
    image: bluewaveuptime/uptime_client:latest
    restart: always
    environment:
      UPTIME_APP_API_BASE_URL: "https://${CONTAINER_NAME}.${TRAEFIK_DOMAIN}/api/v1"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    #ports:
    #  - "8080:80"
    #  - "443:443"
    depends_on:
      - server
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=${TRAEFIK_ENABLE}"
      - "traefik.http.routers.${CONTAINER_NAME}.entrypoints=http"
      - "traefik.http.routers.${CONTAINER_NAME}.rule=Host(`${CONTAINER_NAME}.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.middlewares.${CONTAINER_NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${CONTAINER_NAME}.middlewares=${CONTAINER_NAME}-https-redirect"
      - "traefik.http.routers.${CONTAINER_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${CONTAINER_NAME}-secure.rule=Host(`${CONTAINER_NAME}.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.${CONTAINER_NAME}-secure.tls=true"
      - "traefik.http.routers.${CONTAINER_NAME}-secure.service=${CONTAINER_NAME}"
      - "traefik.http.services.${CONTAINER_NAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=frontend"
    env_file:
      - .env
  server:
    image: bluewaveuptime/uptime_server:latest
    restart: always
    #ports:
    #  - "5000:5000"
    depends_on:
      - redis
      - mongodb
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/uptime_db
      - REDIS_HOST=redis
      - PAGESPEED_API_KEY=${PAGESPEED_API_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend
      - frontend
  redis:
    image: bluewaveuptime/uptime_redis:latest
    restart: always
    #ports:
    #  - "6379:6379"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      - backend
  mongodb:
    image: bluewaveuptime/uptime_database_mongo:latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mongo/data:/data/db
    command: ["mongod", "--quiet"]
    #ports:
    #  - "27017:27017"
    networks:
      - backend

networks:
  backend:
    internal: true
  frontend:
    external: true