name: ${CONTAINER_NAME}

networks:
    frontend:
        external: true

services:
    server:
        container_name: ${CONTAINER_NAME}
        hostname: ${CONTAINER_NAME}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./data/:/data/
        restart: unless-stopped
        #ports:
        #    - 8001:80
        image: vaultwarden/server:latest
        networks:
            - frontend
        env_file:
            - .env
        labels:
            - "traefik.enable=${TRAEFIK_ENABLE}"
            - "traefik.http.routers.${CONTAINER_NAME}.entrypoints=http"
            - "traefik.http.routers.${CONTAINER_NAME}.rule=Host(`${CONTAINER_NAME}.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.middlewares.${CONTAINER_NAME}-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.${CONTAINER_NAME}.middlewares=${CONTAINER_NAME}-https-redirect"
            - "traefik.http.routers.${CONTAINER_NAME}-secure.entrypoints=https"
            - "traefik.http.routers.${CONTAINER_NAME}-secure.rule=Host(`${CONTAINER_NAME}.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.${CONTAINER_NAME}-secure.tls=true"
            - "traefik.http.routers.${CONTAINER_NAME}-secure.service=${CONTAINER_NAME}"
            - "traefik.http.services.${CONTAINER_NAME}.loadbalancer.server.port=80"
            - "traefik.docker.network=frontend"